In [3]:
#Step1
#NumPyをインポートするコードを記述する
import numpy as np
#Step2
#AとBの行列を格納する多次元配列のコードを記述する
A=np.array([[0,1],[2,3],[4,5]])#3×2行列
B=np.array([[0,1,2,3],[4,5,6,7]])#2×4行列

#Step3.
#行列の積の計算をするコードを記述する
C=np.dot(A,B)
#Step4.
#Step3.の計算結果を表示するコードを記述する
print(C)
#Step5.
#行列の要素の最大値を求めるコードを記述する
print(np.max(C))

[[ 4  5  6  7]
 [12 17 22 27]
 [20 29 38 47]]
47
